### ISSUE TITLE
Generate nice tree decomposition

### ISSUE THREAD

**Issue by jfhn** [manuEbg/thm-ptas#18]
To be able to use dynamic programming with a tree decomposition we need to convert it into a _nice_ tree decomposition.
See:
- Dynamic programming on Nice Tree Decompositions: https://studenttheses.uu.nl/bitstream/handle/20.500.12932/19547/thesis_lwgraaff_v2.pdf
- The Fine Details of Fast Dynamic Programming over Tree Decompositions: https://sites.cs.ucsb.edu/~daniello/papers/treewidthDpDetails.pdf

Depends on #7

**Comment by manuEbg** [comment]
closed since #50
