### ISSUE TITLE
Cut Graph in Donuts

### ISSUE THREAD

**Issue by manuEbg** [manuEbg/thm-ptas#21]
```rust
Dcel::find_donuts(&self, k: usize) -> Vec<SubDcel>  ...
```
```
struct SubDcel {
   sub: Dcel,
   parent: &Dcel,
   mapping: ???
}
```
`SubDcel` : 
Dcel + Mapping to ParentDcel

**Comment by manuEbg** [comment]
I think the problems with triangulation on donuts are result, of the sub-dcel not being build correctly.
The following function in the SubDcelBuilder pushes an arc and its twin at the same time.
```rs
    pub fn push_arc(&mut self, a: &arc::Arc) {
        let src = self.push_vertex(a.src());
        let dst = self.push_vertex(a.dst());
        self.dcel_builder.push_arc(src, dst);
        self.dcel_builder.push_arc(dst, src);
    }
```
This is wrong since the dcelBuilder needs all arc of a vertex in the correct order (counter clockwise). 

### Suggestion
something like this
```
for v in Donut
    for a in v.arcs()
        if a.dst() is a part of the donut
            SubDcelBuilder.push(a)    // Only this arc! not its twin
       end
   end
end
```

**Comment by manuEbg** [comment]
Currently each Donut holds a copy of the main Graph.
```rs
pub struct SubDcel {
    pub dcel: Dcel,
    pub sub: Dcel,
    pub arc_mapping: Vec<arc::ArcId>,
    pub vertex_mapping: Vec<vertex::VertexId>,
}
```
We might use this on huge graphs with a lot of donuts. Therefore i think it would be a lot more efficent to use a reference to the main graph.

**Comment by gsass1** [comment]
Couldn’t do that because the Rust borrow checker made everything kaputt when I tried.

**Comment by manuEbg** [comment]
> We need a list of `VertexIds` to identify all the vertices of the innere ring. This is necessary to correctly approximate treedecompositions.

**Comment by manuEbg** [comment]
work is happening here #15 #56
